"""
Operator Agent — actually DOES the work, not just plans it.

For each step of an approved initiative the Operator decides:
  • AUTO       — it can complete this now (write the product, draft the posts,
                 generate the files). It does so and saves real deliverables.
  • NEEDS_YOU  — a real human signup / verification / payment is unavoidable.
                 It produces a minimal one-click handoff packet (pre-filled
                 details + exact link) so the CEO spends ~60 seconds, then
                 stores any account it tells the CEO to create in the vault.

Hard reality baked in: LLMs over a text API cannot pass CAPTCHAs, email/phone
verification, or ToS-restricted automated signups. The Operator is honest about
that line instead of pretending to click buttons it can't click.
"""

import os
import re

from core import llm, state, vault

SYSTEM = """You are the Operator Agent — the doer of a lean AI startup. You take
a single task step and complete it yourself. The CEO will NOT create any new
accounts, sign up for anything, or do any manual tasks.

CRITICAL RULES:
- NEVER classify a step as NEEDS_YOU because an account doesn't exist.
  The strategy is already constrained to platforms the CEO has. If a step
  involves a platform the CEO has (GitHub, Reddit, Google, social media),
  treat it as AUTO and produce the content/files ready to use.
- NEVER ask the CEO to create a Pinterest, Canva, Etsy, Gumroad, or ANY
  other new account. Those ideas should never reach you — but if they do,
  reroute the step to an equivalent action on GitHub, Reddit, or Google Docs.
- NEEDS_YOU is only valid for: physically clicking "Publish" on a post
  (provide the exact text to paste), or entering a PayPal.me link the
  CEO already has.

You can fully do: writing product content, drafting posts/emails/copy, creating
file-based deliverables (templates, guides, markdown sites, CSVs, scripts),
research, SEO text, naming, pricing, GitHub Pages HTML/CSS.

For each step, reply in EXACTLY this format:

CLASSIFY: AUTO   (or)   CLASSIFY: NEEDS_YOU
DELIVERABLE: <if AUTO: the actual finished content/work product, in full>
FILENAME: <if AUTO and it should be saved as a file: a short filename like templates.md, else blank>
HANDOFF: <if NEEDS_YOU: one clear sentence — ONLY for publishing/posting, not signups>
LINK: <if NEEDS_YOU: the exact URL, else blank>
ACCOUNT_SERVICE: <if NEEDS_YOU and it's creating an account: service name e.g. Gumroad, else blank>
SUGGESTED_EMAIL: <if creating an account: a +alias email suggestion, else blank>"""

_DELIVERABLES_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "deliverables")


def run_step(initiative_id, step_num, initiative_title, step_desc, base_email="you@example.com", emit=None):
    """Have the Operator actually attempt one step. Returns ('auto'|'needs_you', detail)."""
    prompt = f"""Initiative: {initiative_title}
Task step: {step_desc}
CEO base email for account aliases: {base_email}

Do this step now if you can. If a real human signup/verification is truly
unavoidable, hand it off minimally."""

    reply = llm.ask(SYSTEM, prompt)
    fields = _parse(reply)

    classify = (fields.get("classify") or "AUTO").upper()

    if "NEEDS_YOU" in classify:
        handoff = fields.get("handoff") or step_desc
        link = fields.get("link") or ""
        service = fields.get("account_service") or ""
        suggested_email = fields.get("suggested_email") or ""

        # Build the minimal handoff message
        msg = handoff
        if service and suggested_email:
            msg += f"  (suggested login email: {suggested_email})"

        state.add_task_blocker(initiative_id, msg, link)

        # If it's an account, pre-register a vault slot so the CEO can fill the password
        if service and not vault.service_exists(service):
            vault.add_account(
                service=service,
                email=suggested_email or base_email,
                url=link,
                notes=f"Auto-created slot for initiative #{initiative_id}. Add password after signup.",
            )
            if emit:
                emit(f"Reserved vault slot for {service} — add your password after signup.")

        if emit:
            emit(f"Step {step_num} needs you (~60s): {handoff[:80]}")
        return "needs_you", f"⚠ NEEDS YOU: {msg}" + (f"\n{link}" if link else "")

    # AUTO path — actually produce the deliverable
    deliverable = fields.get("deliverable") or reply
    filename = fields.get("filename") or ""

    if filename:
        path = _save_deliverable(initiative_id, filename, deliverable)
        # Expose it as a clickable result (local file path)
        state.add_task_result(initiative_id, f"📄 {filename}", _file_url(path), "Generated by Operator")
        if emit:
            emit(f"Step {step_num} done — produced {filename}")
    else:
        if emit:
            emit(f"Step {step_num} done — completed by Operator")

    return "auto", deliverable


def _save_deliverable(initiative_id, filename, content):
    """Write a generated work product to data/deliverables/."""
    safe = re.sub(r"[^a-zA-Z0-9._-]", "_", filename)
    folder = os.path.join(_DELIVERABLES_DIR, f"initiative_{initiative_id}")
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, safe)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


def _file_url(path):
    """Turn a local path into a file:// URL the browser can open."""
    return "file:///" + os.path.abspath(path).replace("\\", "/")


def _parse(reply):
    """Pull the labeled fields out of the Operator's reply."""
    fields = {}
    current = None
    buf = []
    keys = {"CLASSIFY", "DELIVERABLE", "FILENAME", "HANDOFF", "LINK",
            "ACCOUNT_SERVICE", "SUGGESTED_EMAIL"}
    for line in reply.splitlines():
        m = re.match(r"([A-Z_]+)\s*:\s*(.*)", line)
        if m and m.group(1) in keys:
            if current:
                fields[current.lower()] = "\n".join(buf).strip()
            current = m.group(1)
            buf = [m.group(2)]
        elif current:
            buf.append(line)
    if current:
        fields[current.lower()] = "\n".join(buf).strip()
    return fields
